# Starship Configuration

format = """
[$fill](fg:whitealt)\
$cmd_duration\
$line_break\
$username\
$directory\
$package\
$c\
$cmake\
$elm\
$golang\
$java\
$kotlin\
$gradle\
$lua\
$nodejs\
$ocaml\
$python\
$rust\
$scala\
$zig\
$direnv\
$env_var\
$fill\
$git_status\
$jobs\
$line_break\
$sudo\
$git_branch\
$character
"""
add_newline = false
scan_timeout = 150

# [status] # customized end segments for the prompt based on exit code
# disabled = false
# symbol = "[ê©É](fg:blue)"
# success_symbol = "[‚óè](fg:success)"
# not_executable_symbol = "[ê©É](fg:bright-red)"
# not_found_symbol = "[?](fg:bright-red)"
# sigint_symbol = "[‚àÖ](fg:yellow)"
# signal_symbol = "[‚Ä•](fg:success)"
# style = "$style"
# map_symbol = true
# recognize_signal_code = true
# format = '[$symbol ]($style)'

[character]
success_symbol = '[‚ùØ](fg:cyan)'
error_symbol = '[‚ùØ](fg:purple)'
vimcmd_symbol = '[‚óÜ](green)'

[username]
disabled = false
show_always = true
aliases = { 'u0_a343' = 'akal' }
style_root = "bold fg:red"
style_user = "fg:bright-blue"
format = "[‚ñå](fg:blue)[$user]($style) [‚Ä∫](blue) "

[cmd_duration]
format = '[ $duration ]($style)'
min_time = 2_500
style = 'dimmed fg:bright-cyan'

[jobs]
disabled = false
symbol = '‚óª'
style = "bold fg:red"
number_threshold = 1
symbol_threshold = 1
format = '[$symbol]($style)'

[directory]
style = 'yellow'
fish_style_pwd_dir_length = 2
home_symbol = '‚åÇ Home'
read_only = '‚ö†'
read_only_style = 'bold bright-red'
format = '[$path]($style)[$read_only]($read_only_style)'
truncation_length = 1
truncation_symbol = "‚Äî"

[direnv]
disabled = false

[git_branch]
format = '$symbol[$branch(:$remote_branch)]($style) '
symbol = '[‚ñå](blue)'
style = 'dimmed white'
truncation_length = 4
truncation_symbol = ''

[git_status]
disabled = false
style = "purple"
stashed = "[*](bright-white)"
staged = "[#](bright-white)"
modified = "[+](bright-white)"
typechanged = "[√∑](bright-white)"
untracked = "[√ó](bright-white)"
renamed = "[‚â°](bright-white)"
deleted = "[-](bright-white)"
conflicted = "[‚öê](bright-white)"
ahead = "[‚Ü•](bright-white)"
behind = "[‚Üß](bright-white)"
up_to_date = "[^](blue)"
diverged = """\
    [‚§ö](fg:yellow)\
    [${ahead_count}](fg:#64b141)\
    [‚áµ](bold fg:white)\
    [${behind_count}](fg:#e03c31)\
"""
format = "[„Äå$stashed$staged$untracked$modified$renamed$deleted$conflicted$ahead_behind„Äç]($style)"

# Language Symbols
[c]
format = '[ $symbol]($style)'
symbol = 'Óòû '
style = 'blue'

[rust]
format = '[ $symbol]($style)'
symbol = 'Óöã '
style = 'red'

[cmake]
format = '[ $symbol]($style)'
symbol = 'Óûî '

[elm]
format = '[ $symbol]($style)'
symbol = 'Óò¨ '

[golang]
format = '[ $symbol]($style)'
symbol = 'Û∞üì '

[java]
format = '[ $symbol]($style)'
symbol = 'Óú∏ '

[kotlin]
format = '[ $symbol]($style)'
symbol = 'Óò¥ '

[gradle]
format = '[ $symbol]($style)'
symbol = 'Óü≤ '

[lua]
format = '[ $symbol]($style)'
symbol = 'Ó†¶ '

[nodejs]
format = '[ $symbol]($style)'
symbol = 'ÓµÑ '

[ocaml]
format = '[ $symbol]($style)'
symbol = 'Ó°é '

[python]
format = '[ $symbol]($style)'
symbol = 'Óúº '

[scala]
format = '[ $symbol]($style)'
symbol = 'Óú∑'

[zig]
format = '[ $symbol]($style)'
symbol = 'Óö© '

[package]
disabled = true

[fill]
symbol = " "
style = '$style'

