# Starship Configuration

format = """
[$fill](fg:defaultalt)\
$cmd_duration\
$line_break\
$username\
$directory\
$package\
$c\
$cmake\
$elm\
$golang\
$java\
$kotlin\
$gradle\
$lua\
$nodejs\
$ocaml\
$python\
$rust\
$scala\
$typst\
$zig\
$meson\
$nats\
$direnv\
$env_var\
[$fill](fg:uibackgroundalt bg:uibackgroundalt)\
$jobs\
$status\
$line_break\
$sudo\
$git_branch\
${custom.dot}\
$character
"""

right_format = """
$git_status\
"""
add_newline = false
palette = 'blackdiamond'
scan_timeout = 150

# Palettes Configuration
[palettes.ayudark]
main-dark = '#000000'
main-light = '#2E3338'
text = '#dfdfdf'
text-light = '#ffffff'
text-dark = '#8f8f8f'
text-disabled = '#7f7f7f'
primary = '#0f8fcf'
info = '#FFD166'
success = '#06D6A0'
error = '#EF476F'
warn = '#E55934'
main = '#0f1419'
background = '#0f1419'
foreground = '#e6e1cf'
cursor = '#f29718'
selection = '#253340'
cursorAccent = '#0f1419'
black = '#000000'
red = '#ff3333'
green = '#b8cc52'
yellow = '#e7c547'
blue = '#36a3d9'
magenta = '#f07178'
cyan = '#95e6cb'
white = '#ffffff'
bblack = '#323232'
bred = '#ff6565'
bgreen = '#eafe84'
byellow = '#fff779'
bblue = '#68d5ff'
bmagenta = '#ffa3aa'
bcyan = '#c7fffd'
bwhite = '#ffffff'

[palettes.blackdiamond]
# colors
blue = '#11B7D4'
green = '#00a884'
greenalt = '#3585bb'
orange = '#d4770c'
pink = '#d46ec0'
purple = '#a85ff1'
red = '#E35535'
salmon = '#c62f52'
turquoize = '#38c7bd'
yellow = '#c7910c'
# levels
danger = '#E35535'
info = '#11B7D4'
success = '#00a884'
warning = '#d4770c'
# ui
border = '#040506'
default = '#bec6d0'
defaultMain = '#a0acbb'
defaultalt = '#475262'
primary = '#11B7D4'
primaryalt = '#1c2027'
uibackground = '#111418'
uibackgroundalt = '#0c0f11'
uibackgroundmid = '#0f1215'

[status] # customized end segments for the prompt based on exit code
disabled = false
symbol = "[$status](underline fg:warning bg:uibackgroundalt)[‚ñê](fg:warning bg:uibackgroundalt)"
success_symbol = "[$status](bold fg:success bg:uibackgroundalt)[‚ñê](fg:green bg:uibackgroundalt)"
not_executable_symbol = "[$status](underline fg:warning bg:uibackgroundalt)[‚ñê](fg:warning bg:uibackgroundalt)"
not_found_symbol = "[$status](underline fg:info bg:uibackgroundalt bg:uibackgroundalt)[‚ñê](fg:info bg:uibackgroundalt)"
sigint_symbol = "[$status](underline fg:danger bg:uibackgroundalt)[‚ñê](fg:danger bg:uibackgroundalt)"
signal_symbol = "[$status](underline fg:success bg:uibackgroundalt)[‚ñê](fg:info bg:uibackgroundalt)"
style = "$style"
map_symbol = true
recognize_signal_code = true
format = '[$symbol]($style)'

[character]
success_symbol = '[‚ñ∂](defaultMain)'
error_symbol = '[‚ñ∂](salmon)'
vimcmd_symbol = '[‚ô¶](green)'

[username]
disabled = false
show_always = true
aliases = { 'u0_a290' = 'akal' }
style_root = "bold fg:danger bg:uibackgroundalt"
style_user = "fg:purple bg:uibackgroundalt"
format = "[‚ñå$user]($style)[‚Ä∫ ](bg:uibackgroundalt)"


[custom.dot]
when = '! git branch'
ignore_timeout = true
symbol = "‚Ä¢"
style = "bold pink"
format = "[$symbol]($style)"

[cmd_duration]
format = '[ $duration ]($style)'
min_time = 1_000
style = 'bold yellow'

[jobs]
disabled = false
symbol = "‚ïé"
style = "fg:red bg:uibackgroundalt"
number_threshold = 1
symbol_threshold = 1
format = '[$number]($style)$symbol'

[directory]
style = 'fg:blue bg:uibackgroundalt'
fish_style_pwd_dir_length = 2
home_symbol = '‚åÇ Home'
format = '[$path]($style)[$read_only]($read_only_style)'
truncation_length = 1
truncation_symbol = "‚Äî"

[direnv]
disabled = false

[git_branch]
format = '$symbol[$branch(:$remote_branch)]($style) '
symbol = '[ ñ§ù ](bold green)'
style = 'underline pink'
truncation_length = 4
truncation_symbol = ''

[git_status]
disabled = false
style = "fg:info"
stashed = "[‚òê${count}](bold fg:pink)"
staged = "[‚úî${count}](fg:success)"
modified = "[‚Ü≥${count}](bold fg:info)"
typechanged = "[¬ª${count}](fg:default)"
renamed = "[‚Äó${count}](fg:default)"
untracked = "[?${count}](fg:default)"
deleted = "[!${count}](fg:warning)"
conflicted = "[‚öê${count}](fg:danger)"
ahead = "[‚Ü•${count}](bold fg:#64b141)"
behind = "[‚Üß${count}](bold fg:#e03c31)"
up_to_date = "[ÔÑÇ ](bold fg:greenalt)"
diverged = """\
    [Û∞Ωú ](fg:danger)\
    [${ahead_count}](fg:#64b141)\
    [‚áµ](bold fg:default)\
    [${behind_count}](fg:#e03c31)\
"""
format = "[($stashed$staged$untracked$modified$renamed$deleted$conflicted)($ahead_behind)]($style)"

# Language Symbols
[c]
format = '[ $symbol]($style)'
symbol = 'Óòû '
style = 'blue'

[rust]
format = '[ $symbol]($style)'
symbol = 'Óöã '
style = 'red'

[cmake]
format = '[ $symbol]($style)'
symbol = 'Óûî '

[elm]
format = '[ $symbol]($style)'
symbol = 'Óò¨ '

[golang]
format = '[ $symbol]($style)'
symbol = 'Û∞üì '

[java]
format = '[ $symbol]($style)'
symbol = 'Óú∏ '

[kotlin]
format = '[ $symbol]($style)'
symbol = 'Óò¥ '

[gradle]
format = '[ $symbol]($style)'
symbol = 'Óü≤b'

[lua]
format = '[ $symbol]($style)'
symbol = 'Ó†¶ '

[nodejs]
format = '[ $symbol]($style)'
symbol = 'ÓµÑ '

[ocaml]
format = '[ $symbol]($style)'
symbol = 'Ó°é '

[python]
format = '[ $symbol]($style)'
symbol = 'Óúº '

[scala]
format = '[ $symbol]($style)'
symbol = 'Óú∑'

[typst]
format = '[ $symbol]($style)'
symbol = 'Ó£ä '

[zig]
format = '[ $symbol]($style)'
symbol = 'Óö© '

[package]
disabled = true

[fill]
symbol = "‚Çã"
style = '$style'

