# Starship Configuration

format = """
[‚óã$jobs$fill‚ä≥](color8)$cmd_duration\
$line_break\
[‚ï≠](color4)[ìäà$username$directoryìäâ](color2)\
$package\
$c\
$cmake\
$elm\
$golang\
$java\
$kotlin\
$gradle\
$lua\
$nodejs\
$ocaml\
$python\
$rust\
$scala\
$typst\
$zig\
$meson\
$nats\
$direnv\
$env_var\
[[$fill](color12)‚ä≥](bold color10)\
$line_break\
$sudo\
[‚ï∞](color4)$git_branch$character"""

right_format = """
$git_status\
$line_break\
"""
add_newline = false
palette = 'bearded-bear'
scan_timeout = 150

# Command Duration Configuration
[cmd_duration]
format = '[ $duration ]($style)'
min_time = 1_000
style = 'color11'

# Background Jobs Configuration
[jobs]
disabled = false
symbol = "‚óè"
style = "color3"
number_threshold = 2
symbol_threshold = 1
format = '[$number$symbol]($style)'

# Directory Configuration
[directory]
style = 'color4'
fish_style_pwd_dir_length = 2
home_symbol = '‚åÇ Home'
format = '[$path]($style)[$read_only]($read_only_style)'
truncation_length = 1
truncation_symbol = "‚Äî"

[direnv]
disabled = false

# Git Branch Configuration
[git_branch]
format = '[$symbol](color2)[$branch(:$remote_branch)[¬∑](bold color10)]($style)'
symbol = '[¬∑](bold color13)‚éá '
style = 'color5'
truncation_length = 4
truncation_symbol = ''

# Git Status Configuration
[git_status]
format = '[ÓÇ∂[$all_status$ahead_behind]($style)ÓÇ¥](color8)'
style = 'fg:color3 bg:color8'

# Language Symbols
[c]
format = '[ $symbol]($style)'
symbol = 'Óòû '
style = 'blue'

[rust]
format = '[ $symbol]($style)'
symbol = 'Óöã '
style = 'color1'

[cmake]
format = '[ $symbol]($style)'
symbol = 'Óûî '

[elm]
format = '[ $symbol]($style)'
symbol = 'Óò¨ '

[golang]
format = '[ $symbol]($style)'
symbol = 'Û∞üì '

[java]
format = '[ $symbol]($style)'
symbol = 'Óú∏ '

[kotlin]
format = '[ $symbol]($style)'
symbol = 'Óò¥ '

[gradle]
format = '[ $symbol]($style)'
symbol = 'Óü≤b'

[lua]
format = '[ $symbol]($style)'
symbol = 'Ó†¶ '

[nodejs]
format = '[ $symbol]($style)'
symbol = 'ÓµÑ '

[ocaml]
format = '[ $symbol]($style)'
symbol = 'Ó°é '

[python]
format = '[ $symbol]($style)'
symbol = 'Óúº '

[scala]
format = '[ $symbol]($style)'
symbol = 'Óú∑'

[typst]
format = '[ $symbol]($style)'
symbol = 'Ó£ä '

[zig]
format = '[ $symbol]($style)'
symbol = 'Óö© '

# Character Symbols
[character]
success_symbol = '[ÔÉö](color14)'
error_symbol = '[ÔÉö](color9)'
vimcmd_symbol = '[ÔÖí](color2)'

# Package Configuration
[package]
disabled = true

# Fill Configuration
[fill]
symbol = "‚îà"
style = '$style'

# Palettes Configuration
[palettes.ayudark]
main-dark = '#000000'
main-light = '#2E3338'
text = '#dfdfdf'
text-light = '#ffffff'
text-dark = '#8f8f8f'
text-disabled = '#7f7f7f'
primary = '#0f8fcf'
info = '#FFD166'
success = '#06D6A0'
error = '#EF476F'
warn = '#E55934'
main = '#0f1419'
background = '#0f1419'
foreground = '#e6e1cf'
cursor = '#f29718'
selection = '#253340'
cursorAccent = '#0f1419'
black = '#000000'
red = '#ff3333'
green = '#b8cc52'
yellow = '#e7c547'
blue = '#36a3d9'
magenta = '#f07178'
cyan = '#95e6cb'
white = '#ffffff'
bblack = '#323232'
bred = '#ff6565'
bgreen = '#eafe84'
byellow = '#fff779'
bblue = '#68d5ff'
bmagenta = '#ffa3aa'
bcyan = '#c7fffd'
bwhite = '#ffffff'

[palettes.bearded-bear]
background = '#1c2433'
foreground = '#d0d7e4'
cursor = '#eacd61'
color0 = '#1c2433'
color8 = '#3e4f71'
color1 = '#e35535'
color9 = '#ff4319'
color2 = '#3cec85'
color10 = '#29ff82'
color3 = '#eacd61'
color11 = '#ffd94c'
color4 = '#69c3ff'
color12 = '#69c3ff'
color5 = '#f38cec'
color13 = '#ff80f6'
color6 = '#22ecdb'
color14 = '#0fffeb'
color7 = '#d0d7e4'
color15 = '#ffffff'
